app = "twilio-speechmatics-pilot"
primary_region = "fra"

[build]
  [build.args]
    NODE_VERSION = "18"

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  [[services.ports]]
    port = 8080